/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e444b7b7-3dc5-4e2a-b416-57ac2d0c10e5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WaOwy4UXy",
    "aws_user_pools_web_client_id": "2r31j7emh3eicphach02ruo4bj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hdveth2odrbkfpqbi5avw4rbxa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-avoca3g3tjgulmmwgmu2ph4pkm"
};


export default awsmobile;
